fix: #5 by changing UpperFirst.transform logic
mrgnhnt96/change_case pull request #6
Opened 2024-06-02 19:31 UTC by zmuranaka

* No longer crashes when a match is never found (such as if the user changed ChangeCaseConfig.stripPatterns)

2024-06-02 23:12 UTC, mrgnhnt96 requested changes
This change looks great! Can you add a few tests to validate that it works and fixes the crash?

2024-06-04 02:31 UTC, zmuranaka commented
Added tests to ensure `Capital` & `UpperFirst` are working as expected now.
Specifically the crash is tested [here](https://github.com/zmuranaka/change_case/blob/main/test/src/cases/capital_test.dart#L52)

2024-06-04 16:31 UTC, mrgnhnt96 approved these changes
Thanks for contributing! I'll get this released asap 🚀

2024-06-04 16:46 UTC, merged

2024-06-04 17:00 UTC, mrgnhnt96 commented
This is released in version [2.1.0](https://pub.dev/packages/change_case/versions/2.1.0)